### PR TITLE
✏️ Update copy and site header

### PR DESCRIPTION
**Pull request by alsoknownaslj**
- Removed "Security" and "DAO" from header links (looks cleaner and having DAO in the header makes it sound like we are a DAO already) + dded "Web3 Pledge" to make the page more visible.
- Edited newsletter signup copy
- Other minor copy polish for clarity, grammar, and pith.

PR 115_1
PR 115_2
PR 115_3
PR 115_4

### CODE REVIEW

**Comment by VladUXUI** [comment]
Looks good!

**Comment by mhluongo** [comment]
Though if you do want to do those things this time... :point_right: :point_left: :blush:

**Comment by puppycodes** [comment]
@alsoknownaslj 🔥 Oh hell yeah!! 😎

**Comment by greg-nagy** [comment]
> Include testing instructions! Yes, in this case that feels like overkill... but it's a good practice to follow.

testings steps: check the 
CleanShot 2022-11-04 at 15 03 43

**Review by greg-nagy — APPROVED** [review]
let's go!!!! :)

**Review by VladUXUI — APPROVED** [review]
Looking good 🚀 
Also, excited for this @alsoknownaslj !

**Pull request merged**
