### PR TITLE
Orgify: Move all relevant tally.cash references to tallyho.org

### PR DESCRIPTION
**Pull request by Shadowfiend**
To be checked: is the manifest dApp backend auto-deployed, or do we need to deploy manually?

blog.* and doc.* domains are left as-is for now.

### CODE REVIEW

**Comment by Shadowfiend** [comment]
I think this is good to merge, but I think someone needs to deploy the Firebase changes. Tagging @greg-nagy because I'm not sure the procedure on that one.

**Comment by Shadowfiend** [comment]
(Also would be good to drop a brief README explaining or linking to instructions in the `manifesto-dapp-backend` directory.)

**Review by greg-nagy — APPROVED** [review]
let's goooo

**Comment by greg-nagy** [comment]
docs PR : https://github.com/tallycash/tallyho.org/pull/117

**Pull request merged**
